config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :members, skip: :registrations
  as :member do
    get 'members/edit', to: 'devise_invitable/registrations#edit', as: 'edit_member_registration'
    put 'members', to: 'devise_invitable/registrations#update', as: 'member_registration'
  end

  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'en_savoir_plus', to: 'static_pages#about_us', as: 'about_us'
  get 'faq', to: 'static_pages#faq', as: 'faq'

  resources :missions do
    resource :enrollments, only: %i[new create destroy]
  end

  resources :productors
  resources :infos
  resources :documents, only: %i[index create destroy]
  resources :members, only: %i[index show edit update]
  resources :member_static_slots, only: %i[destroy]
  mount Thredded::Engine => '/forum'
end

app/models/productor.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: productors
#
#  id           :bigint(8)        not null, primary key
#  name         :string
#  description  :text
#  phone_number :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  website_url  :string
#  local        :boolean          default(FALSE)
#

# Ressource for the members to get products from (vegetables...), and are managed by the 'management/supply' team
class Productor < ApplicationRecord
  extend Enumerize

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true, update_only: true
  has_and_belongs_to_many :missions, dependent: :nullify
  has_and_belongs_to_many :managers, class_name: "Member", dependent: :nullify
  has_one_attached :avatar
  has_many_attached :catalogs

  enumerize :category, in: %i[bio_and_ethical bio conventional]

  validates :name, presence: true, uniqueness: true
end

app/controllers/productors_controller.rb
# frozen_string_literal: true

# Ressource for the members to get products from (vegetables...), and are managed by the 'management/supply' team
class ProductorsController < ApplicationController
  before_action :authenticate_member!
  before_action :set_authorized_productor, only: %i[show edit update destroy]

  def index
    @productors = Productor.includes :address, :avatar_attachment
  end

  def new
    @productor = authorize Productor.new

    # address form generator
    @productor.build_address
  end

  def create
    @productor = authorize Productor.new(permitted_params)
    if @productor.save
      flash[:notice] = translate "activerecord.notices.messages.record_created",
                                 model: Productor.model_name.human
      render :show
    else
      flash[:error] = translate "activerecord.errors.messages.creation_fail",
                                model: Productor.model_name.human
      render :new
    end
  end

  def show; end

  def edit
    @productor.build_address if @productor.address.nil?
  end

  def update
    if @productor.update(permitted_params)
      flash[:notice] = translate "activerecord.notices.messages.update_success"
      render :show
    else
      flash[:error] = translate "activerecord.errors.messages.update_fail"
      render :edit
    end
  end

  def destroy
    if @productor.destroy
      flash[:notice] = translate "activerecord.notices.messages.record_destroyed",
                                 model: Productor.model_name.human
    else
      flash[:error] = translate "activerecord.errors.messages.destroy_fail",
                                model: Productor.model_name.human
    end
    redirect_to productors_path
  end

  private

  def permitted_params
    params.require(:productor).permit(:name, :description, :local,
                                      :phone_number, :website_url, :avatar,
                                      :category,
                                      catalogs: [],
                                      address_attributes: [
                                        :id, :postal_code, :city, :street_name_1,
                                        :street_name_2, :_destroy, coordinates: []
                                      ])
  end

  def set_authorized_productor
    @productor = authorize Productor.find(params[:id])
  end
end

app/helpers/productors_helper.rb
# frozen_string_literal: true

module ProductorsHelper
end

app/views/productors/_coordinates_fields.html.erb
<div class="col-lg-12 mb-3">
  <div class="field">
    <%= f.label :coordinates, "Coordonées GPS" %>

    <div id="productor_address_attributes_coordinates", class="d-flex">
      <%= text_field_tag "productor[address_attributes][coordinates][]",
        (coordinates.nil? ? nil : coordinates[0]),
        class: "form-control mr-2", placeholder: "latitude" %>

      <%= text_field_tag "productor[address_attributes][coordinates][]",
        (coordinates.nil? ? nil : coordinates[1]),
        class: "form-control", placeholder: "longitude" %>
    </div>
  </div>
</div>

app/views/productors/_form.html.erb
<div class="form-default mt-4" >

<%= form_with model: productor, local: true do |f| %>
  <div class="col">
    <div class="col-lg-12">
      <div class="field">
        <%= f.label :name, Productor.human_attribute_name(:name)%><br />
        <%= f.text_field :name, class: "form-control form-control-lg", required: true %><br />
      </div>

      <div class="field ">
        <%= f.label :description, Productor.human_attribute_name(:description)%><br />
        <%= f.hidden_field :description %><br />
        <trix-editor input="productor_description"></trix-editor>
      </div>

      <div class="field mt-4">
        <%= label_tag translate("main_app.views.productors.edit.type.label",
                               model: Productor.model_name.human) %>
        <br>
        <div class="px-3">
          <%= f.label :local, t("main_app.views.productors.edit.type.local")%>
          <%= f.radio_button :local, true %><br />
          <%= f.label :local, t("main_app.views.productors.edit.type.supplier")%>
          <%= f.radio_button :local, false  %><br /><br />
        </div>
      </div>

      <div class="field mt-4">
        <%= f.label translate(".category") %>
        <%= f.select :category, Productor.category.options, class: 'form-control' %>
        <br>
        <div class="px-3">
        </div>
      </div>

      <br>

      <div class="field">
        <%= f.label :phone_number, Productor.human_attribute_name(:phone_number) %><br />
        <%= f.text_field :phone_number, class: "form-control form-control-lg" %><br />
      </div> 

      <div class="field">
        <%= f.label :website_url, Productor.human_attribute_name(:website_url) %><br />
        <%= f.text_field :website_url, class: "form-control form-control-lg" %><br />
      </div>

      <div class="field">
        <%= f.label :avatar, Productor.human_attribute_name(:avatar)%><br />
        <%= f.file_field :avatar, accept: 'image/png, image/gif, image/jpeg', class: "btn" %><br />
      </div> 
      <hr>

      <div class="field">
        <%= f.label :catalogs, Productor.human_attribute_name(:catalogs)%><br />
        <%= f.file_field :catalogs, multiple: true, class: "btn" %><br />
      </div> 
    </div>
  </div>
  <br />

  <%= f.fields_for :address, productor.address do |address_fields| %>
    <%= render 'layouts/address_fields', coordinates: productor.address.coordinates,
                                         f: address_fields %>
  <% end %>
  
  <div class="actions">
    <%= f.submit nil,
      class: "btn-update btn btn-styled btn-lg btn-block btn-base-1 mt-4" %>
  </div>
  
<% end %>

app/views/productors/_productors.html.erb
<% productors.each do |productor| %>
<div class="col-lg-4 mb-2">
  <div class="block block--style-3">
    <div class="profile-picture profile-picture--style-1">
      <% if productor.avatar.attached? %>
          <%= image_tag productor.avatar %>
      <% else %>
          <img src="https://image.flaticon.com/icons/svg/0/93.svg">
      <% end %> 
    </div>

    <div class="block-body text-center">
      <h3 class="heading heading-6 strong-600 mb-0 mb-0"><%= productor.name %></h3>
      <br />
      <h3 class="heading heading-light heading-sm strong-300"><%= productor.address.city unless productor.address.nil? %></h3>
      <h3 class="heading heading-light heading-sm strong-300"><%= productor.phone_number %></h3>
      <h3 class="heading heading-light heading-sm strong-300"><%= productor.website_url %></h3>
                  
      <%= link_to "Voir Producteur", productor_path(productor.id) , class: "btn btn-base-1 btn-shadow btn-circle px-4 mt-2" %>
    </div>
  </div>
</div>
<% end %>

app/views/productors/_suppliers.html.erb
<div class="container">
  <div class="widget mt-4">
    <div class="row-wrapper">
      <ul class="nav nav-tabs justify-content-center mb-5" role="tablist">
        <% Productor.category.values.each_with_index do |category, index| %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if index.zero? %>" data-toggle="tab" href="#<%= category %>">
              <%= t "enumerize.productor.category.#{category}" %>
            </a>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="row-wrapper">
      <div class="tab-content" id="myTabContent">
        <% Productor.category.values.each_with_index do |category, index| %>
          <div class="tab-pane fade show <%= 'active' if index.zero? %>" id=<%= category %> role="tabpanel" aria-labelledby="<%= category %>-tab">
            <div class="row cols-md-space cols-sm-space cols-xs-space">
              <%= render partial: "productors",
                locals: { productors: suppliers.select {|productor|
                productor.category == category 
              }} %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/productors/edit.html.erb
<div class="slice sct-color-2 body-wrap container">
  <div class="row justify-content-center">
    <section class="card form-card form-card--style-1">
      <header class="form-header text-center">
        <div class="profile-picture profile-picture--style-2">
          <% if @productor.avatar.attached? %>
            <%= image_tag @productor.avatar %>
          <% else %>
            <img src="https://image.flaticon.com/icons/svg/0/93.svg" class="profil-img">
          <% end %>
        </div>
      </header>

      <main class="form-body">
        <div class="text-center px-2">
          <h2 class="heading strong-400 mb-0">
            <%=
              translate "main_app.views.productors.edit.title",
                model: Productor.model_name.human
              %>
          </h2>
        </div>

      <%= render partial: 'form', locals: {productor: @productor} %>

      </main>
    </section>
  </div>
</div>

app/views/productors/index.html.erb
<div class="container">
	<div class="widget mt-4">

		<div class="row-wrapper">
			<ul class="nav nav-tabs justify-content-center mb-5" role="tablist">
				<li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#locals">
            <%= translate "main_app.views.productors.index.tabs.locals" %>
          </a>
				</li>
				<li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#suppliers">
            <%= translate "main_app.views.productors.index.tabs.suppliers" %>
          </a>
				</li>
			</ul>
		</div>

		<div class="row-wrapper">
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade show active" id="locals" role="tabpanel" aria-labelledby="locals-tab">
					<% if super_admin? || admin? %>
						<div class="d-flex">
              <%= link_to  "Ajouter un producteur",
                new_productor_path,
                class: "btn btn-base-1 btn-shadow btn-circle px-4 mx-auto mb-4" %>
						</div>
					<% end %>

					<div class="row cols-md-space cols-sm-space cols-xs-space">
            <%= render partial: "productors",
              locals: { productors: @productors.select {|productor|
                          productor.local == true 
                      }} %>
					</div>
				</div>

				<div class="tab-pane fade" id="suppliers" role="tabpanel" aria-labelledby="suppliers-tab">
          <p>
            Nos fournisseurs proposent toujours de nouveaux produits, les tarifs baissent ou augmentent...
            <br>
            <br>
            La liste de fournisseurs  présentée ci-dessous est en perpétuel mouvement.
            <br>
            <br>
            Notre travail de recherches et de comparaisons est constant au gré de vos demandes pour la satisfaction de tous.
            <br>
            Nous sélectionnons les meilleurs qualité/prix. 
            Rappelons que les meilleures qualités ne sont pas obligatoirement plus chères que les autres 
            car de nombreux paramètres jouent  dans la composition du prix d’un produit. 
            Azade sera parmi nous après la crise sanitaire et nous expliquera tout cela.
            <br>
            <br>
            Au fil du temps, apparaîtront sur nos étiquettes les renseignements suivants avec ce codage :
            O : origine, E : équitable, S : solidaire, P/T : producteur/ transformateur, D : Demeter ( biodynamie)
          </p>
		
					<% if super_admin? || admin? %>
						<div class="d-flex">
              <%= link_to  "ajouter un fournisseur",
                new_productor_path,
                class: "btn btn-base-1 btn-shadow btn-circle px-4 mb-4 mx-auto" %>
						</div>
					<% end %>

					<div class="row cols-md-space cols-sm-space cols-xs-space">
            <%= render partial: "suppliers",
              locals: { suppliers: @productors.select {|productor|
                          productor.local == false
                      }} %>
					</div>
				</div>
			</div>

		</div>

	</div>
</div>

app/views/productors/new.html.erb
<div class="body-wrap">
  <section class="slice sct-color-2">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="card form-card form-card--style-1">
            <div class="form-header text-center">
              <div class="profile-picture profile-picture--style-2">
                <img src="https://image.flaticon.com/icons/svg/0/93.svg" class="profil-img">
              </div>
            </div>
            <div class="form-body">
              <div class="text-center px-2">
                <h2 class="heading heading-2 strong-400 mb-0">
                  <%= translate "main_app.views.productors.new.title",
                    model: Productor.model_name.human  %>
                </h2>
              </div>
              
              <%= render partial: 'form', locals: {productor: @productor} %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/productors/show.html.erb
<div class="slice ct-color-1 container pt-3 pb-5">
  <div class="row row-no-padding">
    <main class="row align-items-center cols-md-delimited cols-lg-delimited">
      <section class="block block--style-3 col-md-4">
        <header class="profile-picture profile-picture--style-1">
          <% if @productor.avatar.attached? %>
            <%= image_tag @productor.avatar %>
          <% else %>
            <img src="https://image.flaticon.com/icons/svg/0/93.svg" class="profil-img">
          <% end %>
        </header>

        <%# Contact informations %>
        <article class="block-body text-center">
          <h3 class="heading strong-600 mb-0 mb-0">
            <%= @productor.name %>
          </h3>
          <br />
          <h3 class="heading heading-sm strong-300">
            <%= @productor.phone_number if @productor.phone_number.present? %>
          </h3>

          <% if @productor.address.present? %>
            <h3 class="heading heading-light heading-sm strong-300">
              <%= @productor.address.street_name_1 %>
            </h3>
            <h4 class="heading heading-light heading-sm strong-300">
              <%= @productor.address.street_name_2 %>
            </h4>
            <h3 class="heading heading-light heading-sm strong-300">
              <%= @productor.address.city %>
              <%= @productor.address.postal_code %>
            </h3>
          <% else %>
            <h3 class="heading heading-light heading-sm strong-300">
              <%= translate "main_app.views.productors.show.no_address" %>
            </h3>
          <% end %>
          <h3 class="heading heading-light heading-sm strong-300">
            <%= link_to  @productor.website_url, 
              @productor.website_url, 
              class:"" if @productor.website_url.present? %>
        </h3>

        <% if super_admin? || admin? %> 
          <%= link_to translate("main_app.views.application.buttons.edit"), 
            edit_productor_path(@productor.id), 
            class: "btn btn-base-1 btn-shadow btn-circle px-4 mb-4 mt-4" %>
          <%= link_to translate("main_app.views.application.buttons.destroy"), 
            productor_path(@productor.id), 
            method: :delete, 
            class: "btn btn-danger btn-shadow btn-circle px-4 mb-4 mt-4" %> 
        <% end %>
        </article>

      </section>

      <%# Content %>
      <section class="col-md-8 mt-4">
        <h2 class="heading heading-2 strong-300">
          <%= Productor.human_attribute_name(:description) %>
        </h2>
        <p><%= sanitize @productor.description %></p>

        <h2 class="mt-3">
          <%= Productor.human_attribute_name(:catalogs) %>
        </h2>
        <% if @productor.catalogs.attached? %> 
          <% @productor.catalogs.each { |catalog| %>
            <i class="fas fa-file fa-3x"></i>
            <%= link_to "#{catalog.filename}", 
              rails_blob_path(catalog, disposision: 'attachment'), 
              download: true %> 
          <% } %>
        <% else %>
          <%= translate "main_app.views.productors.show.no_catalogs" %>
        <% end %>
      </section>

    </main>
  </div>
  <%= link_to translate("main_app.views.application.buttons.back"), 
    productors_path, 
    class: "fas fa-arrow-left link-retour d-block text-center mt-4 mr-4" %>
</div>