config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :members, skip: :registrations
  as :member do
    get 'members/edit', to: 'devise_invitable/registrations#edit', as: 'edit_member_registration'
    put 'members', to: 'devise_invitable/registrations#update', as: 'member_registration'
  end

  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'en_savoir_plus', to: 'static_pages#about_us', as: 'about_us'
  get 'faq', to: 'static_pages#faq', as: 'faq'

  resources :missions do
    resource :enrollments, only: %i[new create destroy]
  end

  resources :productors
  resources :infos
  resources :documents, only: %i[index create destroy]
  resources :members, only: %i[index show edit update]
  resources :member_static_slots, only: %i[destroy]
  mount Thredded::Engine => '/forum'
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  # The folloiwng line is to deactivate Pundit authorize/policy verification
  # Use it when activating :verify_authorized in application_controller.rb
  # when developping Pundit policies
  # skip_after_action :verify_authorized

  def home; end

  def about_us; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/about_us.html.erb
<section class="slice-xl slice--offset-top has-bg-cover bg-size-cover" style="background-image: url(<%= asset_path('about_us/devanture.jpg') %>); background-position: center;">
  <span class="mask mask-dark--style-3"></span>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="py-5">
          <h2 class="heading heading-inverse heading-xl strong-900 text-capitalize line-height-1_2 animated text-center" data-animation-in="fadeInDownBig" data-animation-delay="200">
            Conditions d'adhésion
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="slice sct-color-1">
  <div class="container">
    <div class="row cols-md-space cols-sm-space cols-xs-space">
      <div class="col-lg-12">
        <div class="card-wrapper">
          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">Fonctionnement</h4>
            <hr class="mt-2 mb-1">
            <div class="row">
              <div class="card-body p-3">
                <%= image_tag "about_us/charte_fonctionnement.jpg", class: "img-fluid" %>
              </div>
            </div>
          </div>

          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">Comment adhérer</h4>
            <hr class="mt-2 mb-5">
            <div class="row ">
              <div class="col-md-4">
                 <%= image_tag "about_us/foule.jpg", class: "img-fluid" %>
              </div>
              <div class="col-md-8">
                <div class="card-body d-flex flex-column align-items-start">
                  <h5 class="heading heading-5 strong-600">Tarifs de la cotisation annuelle</h5>
                  <p> 3 possibilités en fonction de votre situation :</p>
                  <ul>
                    <li>Tarif standard - 20€</li>
                    <li>Tarif chômeur - 5€</li>
                    <li>Tarif spécial - 1€</li>
                  </ul>

                  <h5 class="heading heading-5 strong-600">Où adhérer ?</h5>
                  <p>3 possibilité, au choix :</p>
                  <ul>
                    <li>En ligne : <a href="https://www.helloasso.com/associations/creons-la-coop/adhesions/adhesion-creons-la-coop">Sur HelloAsso</a> (adhésion à 20€ uniquement)</li>
                    <li>Par courrier : remplissez ce <a href="#">formulaire</a>, et envoyez-le avec le règlement à notre adresse administrative (Centre Georges Brassens, 4 rue J.Kennedy - 60100 CREIL)</li>
                    <li><i>Sur place</i>, au magasin : venez nous rencontrer et adhérer directement. Adresse du magasin: 4 allée de la faïencerie, 60100 Creil</li>
                  </ul>

                  <h5 class="heading heading-5 strong-600">Dons</h5>
                  <p>Vous pouvez aussi simplement nous soutenir en nous faisant parvenir vos dons à <a href="https://www.cotizup.com/creonslacoop"> cette adresse</a> </p>
                </div>
              </div>
            </div>
          </div>

          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">Charte des produits de notre magasin</h4>
            <hr class="mt-2 mb-5">
            <div class="row ">
              <div class="col-md-4">
                  <%= image_tag "about_us/hand-coeur.jpg", class: "img-fluid" %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <p>Il s’agit de favoriser les produits issus d’une démarche respectueuse de l’humain et de l’environnement en donnant la priorité à des produits durables issus d’échanges équitables, mais il s’agit aussi de respecter la diversité des membres de l’association ainsi que leurs habitudes culinaires et leur pouvoir d’achat en :</p>
                  <ul>
                    <li>s’adressant en priorité à des producteurs locaux pour favoriser les circuits courts.</li>
                    <li>recherchant à la fois des produits de saison cultivés de manière écologique, de manière raisonnée et de manière conventionnelle. ( 2 ou 3 références qualité/prix)</li>
                    <li>proposant une politique de totale transparence ( Origine, goût, prix, critère qualité santé*)</li>
                    <li>mettant en place une politique de prix juste: un prix le plus accessible possible pour les consommateurs en rémunérant correctement le travail du producteur.</li>
                    <li>proposant 2 à 3 références produits en fonction de la qualité et du prix ( Produits locaux ou non)</li>
                    <li>privilégiant les petites entreprises familiales.</li>
                    <li>luttant contre le gaspillage alimentaire et le sur emballage par la promotion de la vente en vrac.</li>
                    <li>enrichissant et diversifiant les produits au fil du temps et selon les demandes des adhérents.</li>
                    <li>fonctionnant de façon coopérative impliquant chaque participant à notre magasin dans son fonctionnement.</li>
                  </ul>
                  <p>*critère qualité santé : bannir les OGM, les additifs chimiques douteux et dangereux, l’huile de palme et le coprah.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/faq.html.erb
<section class="slice-xl slice--offset-top has-bg-cover bg-size-cover" style="background-image: url(<%= asset_path('about_us/devanture.jpg') %>); background-position: center;">
  <span class="mask mask-dark--style-3"></span>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="py-5">
          <h2 class="heading heading-inverse heading-xl strong-900 text-capitalize line-height-1_2 animated text-center" data-animation-in="fadeInDownBig" data-animation-delay="200">
            Questions fréquentes
          </h2>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="slice sct-color-1">
  <div class="container">
    <div class="row cols-md-space cols-sm-space cols-xs-space">
      <div class="col-lg-12">
        <div class="card-wrapper">
          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">
              Qu'est ce que la CLAC? 
            </h4>
            <hr class="mt-2 mb-1">
            <div class="row">
              <div class="card-body d-flex flex-column align-items-start p-5">
                <h5 class="heading heading-5 strong-600">
                  Qui sommes-nous ?
                </h5>
                <p>
                  La 1ère épicerie coopérative de l’Oise, située dans un local de 200m2 à Creil, s’inspirant de La Louve, 1er supermarché coopératif de France.
                </p>
                <p>
                  Le projet a été lancé en 2016 par deux amies : Karine Hobeika et Jade Goudenège, rapidement rejointes par d’autres personnes qui ensemble ont créé l’association la CLAC en 2017. Ouvert depuis mai 2019, on dénombre plus de 200 adhérents de différents horizons : Creil, Chantilly, Compiègne et même Survilliers, et ce chiffre est en constante augmentation.
                </p>

                <h5 class="heading heading-5 strong-600">
                  Quel modèle suivons-nous ?      
                </h5>
                <p>
                  Nous suivons les modèles des épiceries coopératives comme La Louve, 1 er modèle de ce genre en Europe, importé des USA. 
                </p>

                <h5 class="heading heading-5 strong-600">
                  Comment ça fonctionne ?
                </h5>
                <p>
                  Pour devenir « consom’acteur » au sein de la Créons la Coop, chaque membre adhère à l’association et devient ainsi coopérateur selon ses revenus.
                </p>
                <p>
                  Un coopérateur participe à la vie de la CLAC, il peut voter aux assemblées plénières. Si nécessaire, il peut participer aux choix des produits, des fournisseurs…
                </p>
                <p>
                  Afin que ce système puisse être viable et pérenne, chaque coopérateur s’investit 3H par mois pour le fonctionnement du supermarché selon ses compétences, ses connaissances ou ses aptitudes dans des domaines aussi variés que la comptabilité, la gestion de produits, l’achat des produits, la caisse, la mise en rayon, la propreté du local, l’administratif, l’animation, l’accueil des clients, le bricolage, l’entretien du matériel…
                </p>
                <p>
                  Une fois l’adhésion faite, l’adhérent peut approvisionner son compte en privilégiant le virement bancaire ou un chèque, sous forme d’avance pour permettre l’achat des produits sélectionnés. 
                </p>

                <h5 class="heading heading-5 strong-600">
                  Qu’est-ce qu’on attend de moi ?
                </h5>
                <p>
                  En devenant « Consom’acteur », on devient vraiment acteur de cette épicerie coopérative
                </p>
                <p>
                  Chacun étant à égalité en terme de responsabilité, de tâches… le lien hiérarchique n’existe pas entre les membres.
                </p>
                <p>
                  Chacun-e est invité-e à se former aux outils nécessaires à la réalisation de ses 3 heures. 
                </p>
                <p>
                  Après une période d’observation et d’adaptation, on peut proposer des projets ou des améliorations de l’association.
                </p>

                <h5 class="heading heading-5 strong-600">
                  A quoi ça sert ?
                </h5>
                <p>
                  En supprimant les intermédiaires et en se fournissant directement chez les producteurs, les coopérateurs parviennent à proposer un prix avec une marge très faible. Que ce soient les fruits et légumes, les céréales, les boissons ou les produits d’hygiènes, de cosmétiques, d’entretien, la CLAC vend une majorité de produits nécessaires au quotidien, même les plus classiques, pour favoriser la mixité sociale et culturelle ainsi que les échanges intergénérationnels.
                </p>
                <p>
                  (Il faudrait peut-être ici une phrase pour introduire les suivantes qui sont sous forme de liste de verbes à l'infinitif?)
                </p>
                <p>
                  Proposer des produits de qualité, de saison, issus de producteurs locaux bio ou de l’agriculture raisonnée de préférence.
                </p>
                <p>
                  Mettre en place un mode de consommation coopératif et alternatif.
                </p>
                <p>
                  Sensibiliser à un mode de vie raisonné, éco-responsable et participatif afin de lutter contre le gaspillage : conditionnement vrac privilégié, utilisation de ses propres contenants comme les bocaux, les boites à œufs, les sacs à vrac, à pain…
                </p>
                <p>
                  Créer du lien social et culturel ou encore privilégier la transmission d’une mémoire sur le thème des coopératives notamment à travers des expositions, d’ateliers divers…
                </p>
              </div>
            </div>
          </div>

          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">
              Adhérer à la CLAC
            </h4>
            <hr class="mt-2 mb-5">
            <div class="row ">
              <div class="col-md-8">
                <div class="card-body d-flex flex-column align-items-start">
                  <h5 class="heading heading-5 strong-600">
                    Comment adhérer à la CLAC?
                  </h5>
                  <p>
                    Pour devenir adhérent, il suffit de remplir une fiche d'inscription en magasin ou sur internet et de payer une cotisation annuelle.
                  </p>
                  <p>
                    Les cotisations possibles : 
                  </p>
                  <ul>
                    <li>
                      1€ quartier prioritaire de la ville
                    </li>
                    <li>
                      5€ étudiants et minimas sociaux
                    </li>
                    <li>
                      20€ tarif normal
                    </li>
                    <li>
                      tarif famille : les personnes supplémentaires payent la moitié de la cotisation du membre actif
                    </li>
                  </ul>

                  <h5 class="heading heading-5 strong-600">
                    Combien de temps est valable l'adhésion? 
                  </h5>
                  <p>
                    L'adhésion est valable un an, de date à date.
                  </p>

                  <h5 class="heading heading-5 strong-600">
                    Les Petits paniers de la Clac, c'est quoi ? Qui peut en bénéficier ?    
                  </h5>
                  <p>
                    Nous permettons à chaque adhérent remplissant les conditions ci-dessous de bénéficier de la somme de 12€ toutes les 2 semaines, qui lui est créditée pour lui permettre de contribuer à la réalisation de ses achats.
                  </p>

                  <p>
                    Pour bénéficier de la mise en place de ce dispositif, il faut : 
                  </p>
                  <ul>
                    <li>
                      être adhérent
                    </li>
                    <li>
                      avoir une tarification mini ou solidaire (adhésion à 5€ ou 1€)
                    </li>
                    <li>
                      faire ensuite ses 3h mensuelles
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">
              Débuter sa vie d'adhérent
            </h4>
            <hr class="mt-2 mb-5">
            <div class="row ">
              <div class="col-md-8">
                <div class="card-body">

                  <h5 class="heading heading-5 strong-600">
                    Par où commencer ?      
                  </h5>
                  <p>
                    Une fois l'adhésion acceptée, l'adhérent assiste à la réunion accueil.
                  </p>
                  <p>
                    Ensuite, il pourra s'inscrire sur un créneau horaire et/ou s'engager dans un groupe de travail (groupe commande, accueil, producteurs locaux...). Les personnes inscrites sur le même créneau ou dans le même groupe le guideront pour les tâches à accomplir.
                  </p>

                  <h5 class="heading heading-5 strong-600">
                    Comment connaître les dates de réunions d'accueil ?
                  </h5>
                  <p>
                    Elles sont affichées en magasin, vous les recevez par mail lors de votre adhésion. Elles sont également mises en ligne sur la page Facebook Créons la Coop et sur le forum du site internet du magasin.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div class="card z-depth-2-top">
            <h4 class="heading heading-1 strong-600 line-height-1_8 text-center">
              Comment faire ses 3H
            </h4>
            <hr class="mt-2 mb-5">
            <div class="row ">
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="heading heading-5 strong-600">
                    Comment fait-on pour être formé à la caisse ?      
                  </h5>
                  <p>
                    Pour être formé à la caisse, il faut choisir un horaire où un adhérent est déjà formé à la caisse, ainsi il peut vous transmettre son savoir-faire.  Toutes les procédures, avec des images, sont également précisées en magasin dans des classeurs qu'il faut prendre le temps de consulter pour se les approprier.
                  </p>

                  <h5 class="heading heading-5 strong-600">
                    Peut-on s'inscrire sur un créneau régulier ?      
                  </h5>
                  <p>
                    On peut s'inscrire sur un créneau régulier, il suffit pour cela de s'inscrire sur le planning pour les semaines à venir.
                  </p>

                  <h5 class="heading heading-5 strong-600">
                    Quels sont les différents groupes auxquels les adhérents peuvent participer? 
                  </h5>
                  <p>
                    Les adhérents sont libres de s'engager dans des groupes de travail au sein de la Clac - ces groupes permettent à l'association et au magasin de fonctionner au mieux. Il existe plusieurs groupes, mais il est possible d'en créer pour répondre à un besoin. (exemple de groupe: accueil, comptabilité, gestion du magasin, informatique, culture...)
                  </p>

                  <h5 class="heading heading-5 strong-600">
                    Que faire si on est adhérent mais amené à s'absenter de manière longue avec l'impossibilité de réaliser ses trois heures?
                  </h5>
                  <p>
                    Il convient de prévenir de son absence et d'essayer dans la mesure du possible de récupérer ses heures, tout en prenant en compte le fait que pendant son absence l'adhérent ne réalise pas non plus d'achats.
                  </p>

                  <h5 class="heading heading-5 strong-600">
                    Comment ça se passe si on est en couple, et qu'on peut pas participer tous les deux, mais qu'on veut être tous les 2 adhérents ?
                  </h5>
                  <p>
                    L'adhésion famille est proposée. Les 3 heures peuvent être faites par l'un ou l'autre, ou les 2 à tour de rôle. Bien sûr, si les 2 ont la possibilité et l'envie, ils peuvent s'investir plus, les 3heures sont un minimum. 
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<!-- Force turbolinks reload to load the banner properly on navigation -->
<% provide :head_tags do %>
<meta name="turbolinks-visit-control" content="reload">
<% end %>

<section class="swiper-js-container background-image-holder" data-holder-type="fullscreen" data-holder-offset=".navbar">
	<div class="swiper-container" data-swiper-autoplay="true" data-swiper-effect="slide" data-swiper-items="1" data-swiper-space-between="0">
		<div class="swiper-wrapper">

			<!-- Slide -->
			<div class="swiper-slide" data-swiper-autoplay="8000">
        <div class="slice holder-item holder-item-light has-bg-cover bg-size-cover"
             style="background: url(<%= asset_path('home/panier3.jpg') %>) center/cover;">
					<span class="mask mask-dark--style-3"></span>
					<div class="container d-flex align-items-center">
						<div class="col">
							<div class="row text-center">
								<div class="col-12">
									<h2 class="heading heading-xl strong-400 text-uppercase animated" data-animation-in="fadeInDownBig" data-animation-delay="200">
										Manger mieux, à prix juste
									</h2>
									<p class="heading heading-4 mt-4 animated text-light" data-animation-in="fadeInUp" data-animation-delay="1800">
										Un magasin coopératif<br />
									</p>
									<div class="d-flex flex-column align-items-center mt-5">
										<%= link_to "Espace membres", new_member_session_path, class: "btn btn-lg btn-base-1 btn-circle btn-styled mt-3 animated" %>
										<%= link_to "Comment adhérer", about_us_path, class: "text-white mt-3 animated" %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
    <!-- Add Pagination -->
		<!--<div class="swiper-pagination"></div>-->
	</div>
</section>