config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :members, skip: :registrations
  as :member do
    get 'members/edit', to: 'devise_invitable/registrations#edit', as: 'edit_member_registration'
    put 'members', to: 'devise_invitable/registrations#update', as: 'member_registration'
  end

  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'en_savoir_plus', to: 'static_pages#about_us', as: 'about_us'
  get 'faq', to: 'static_pages#faq', as: 'faq'

  resources :missions do
    resource :enrollments, only: %i[new create destroy]
  end

  resources :productors
  resources :infos
  resources :documents, only: %i[index create destroy]
  resources :members, only: %i[index show edit update]
  resources :member_static_slots, only: %i[destroy]
  mount Thredded::Engine => '/forum'
end

app/models/document.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: documents
#
#  id         :bigint(8)        not null, primary key
#  category   :string           default: weekly_orders
#  published  :boolean          default: false
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Document < ApplicationRecord
  extend Enumerize
  extend ActiveModel::Naming

  has_one_attached :file

  enumerize :category, in: %i[weekly_orders
                              newsletters
                              official_documents
                              financial_documents
                              communications
                              reports
                              procedures
                              questionnaires
                              recipes],
                       default: :weekly_orders

  validates :file, attached: true, size: { less_than: 20.megabytes }, content_type: [
    'application/pdf',
    'application/msword', # .doc
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document', # .docx
    'application/vnd.oasis.opendocument.text', # .odt
    'application/vnd.ms-excel', # .xls
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', # .xlsx
    'text/plain'
  ]
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

# Document management
class DocumentsController < ApplicationController
  def index
    @document = Document.new
    @documents = if member_signed_in?
                   Document.with_attached_file
                 else
                   Document.where(published: true).with_attached_file
                 end
  end

  def create
    @document = authorize Document.new(permitted_params)
    @document.save

    flash.merge! user_feedback_on_create(@document)
    respond_to do |format|
      format.js
      format.html { redirect_to documents_path(anchor: 'documents') }
    end
  end

  def destroy
    @document = authorize Document.find(params[:id])
    @document.destroy
    flash[:notice] = t('activerecord.notices.messages.record_destroyed',
                       model: @document.model_name.singular)

    respond_to do |format|
      format.js
      format.html { redirect_to documents_path(anchor: 'documents') }
    end
  end

  private

  def permitted_params
    params.require(:document).permit(:category, :file)
  end

  def user_feedback_on_create(record)
    if record.persisted?
      message = t("activerecord.notices.messages.record_created",
                  model: @document.model_name.singular)
      { notice: message }
    elsif record.invalid?
      message = record.errors.full_messages.join(', ')
      record.file.purge
      { alert: message }
    else
      message = t('activerecord.errors.messages.creation_fail',
                  model: @document.model_name.singular)
      { error: message }
    end
  end
end

app/helpers/documents_helper.rb
# frozen_string_literal: true

module DocumentsHelper
end

app/views/documents/_document.html.erb
  <tr>
    <td scope="row">
      <%= link_to document.file.filename.to_s,
                  rails_blob_path(document.file, disposition: "attachment") %>
    </td>
    <td scope="row">
      <% if document.file.previewable? %>
        <%= link_to(image_tag(document.file.preview(resize: "90x90")),
                    rails_blob_path(document.file, disposition: "attachment")) %>
      <% else %>
        <%= link_to document.file.filename,
            rails_blob_path(document.file, disposition: "attachment") %>
      <% end %>
    </td>
    <td scope="row">
      <%= link_to translate('main_app.views.application.buttons.destroy'),
        document, method: :delete, id: document.id,
        class: 'btn btn-mini btn-danger',
        data: {
          confirm: t('main_app.views.application.buttons.destroy_confirm', model: Document.model_name),
          remote: true 
        } if policy(Document).destroy? %>
    </td>
  </tr>

app/views/documents/_index.html.erb
<br/>

<div class="card no-border">
  <div class="widget mt-4">
    <div class="row-wrapper">
      <ul class="nav nav-tabs justify-content-center mb-5" role="tablist">
        <% Document.category.values.each_with_index do |category, index| %>
          <li class="nav-item">
            <a class="nav-link <%= 'active' if index.zero? %>" data-toggle="tab" href="#<%= category %>">
              <%= t "enumerize.document.category.#{category}" %>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="row-wrapper">
      <div class="tab-content" id="myTabContent">
        <% Document.category.values.each_with_index do |category, index| %>
          <div class="tab-pane fade show <%= 'active' if index.zero? %>" id=<%= category %> role="tabpanel" aria-labelledby="<%= category %>-tab">
            <div class="row cols-md-space cols-sm-space cols-xs-space">
              <table id="documents" class="table table-sm table-hover">
                <thead>
                  <tr>
                    <th scope="col">Nom du document</th>
                    <th scope="col">Télécharger</th>
                  </tr>
                </thead>

                <tbody>
                  <%= render partial: "documents/document", collection: @documents.select {|document|
                    document.category == category 
                  } %>
                </tbody>
              </table>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/documents/_new.html.erb
<div class="form-default mt-3">
  <%= form_for @document, { remote: true, url: documents_url, method: 'POST' }  do |form|%>
  <div class="col">
    <div class="col-lg-12">

      <div class="field">
        <%= form.label :file, "Ajouter un document" %><br/>
        <%= form.select :category, Document.category.options, class: 'form-control' %>
        <%= form.file_field(:file,
                            accept: 'application/pdf, application/msword, 
                                    application/vnd.openxmlformats-officedocument.wordprocessingml.document, 
                                    application/vnd.oasis.opendocument.text,
                                    application/vnd.ms-excel,
                                    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                            class: "btn-base-1 m-2",
                            required: true) %>
            <%= form.submit value: "Ajouter", class: "btn-base-1 m-2" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/documents/create.js.erb
$('div#<%= @document.category %> > div > table > tbody').append("<%= j render @document unless @document.invalid? %>");

app/views/documents/destroy.js.erb
document.getElementById("<%= @document.id %>").parentNode.parentNode.remove();

app/views/documents/index.html.erb
<div class="container mb-4">
  <div class="main-content">

    <div class="page-title">
      <h2 class="heading-infos heading heading-2 text-uppercase border-bottom border-dark strong-800 mt-5 mb-5">
        Documents
      </h2>
    </div>

    <div class="" id="documents">
      <%= render partial: "documents/new",
                 locals: {document: @document} if policy(Document).create? %>
      <%= render partial: "documents/index", locals: {documents: @documents} %>
    </div>
  </div>
</div>