config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :members, skip: :registrations
  as :member do
    get 'members/edit', to: 'devise_invitable/registrations#edit', as: 'edit_member_registration'
    put 'members', to: 'devise_invitable/registrations#update', as: 'member_registration'
  end

  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get 'en_savoir_plus', to: 'static_pages#about_us', as: 'about_us'
  get 'faq', to: 'static_pages#faq', as: 'faq'

  resources :missions do
    resource :enrollments, only: %i[new create destroy]
  end

  resources :productors
  resources :infos
  resources :documents, only: %i[index create destroy]
  resources :members, only: %i[index show edit update]
  resources :member_static_slots, only: %i[destroy]
  mount Thredded::Engine => '/forum'
end

app/models/info.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: infos
#
#  id         :bigint(8)        not null, primary key
#  content    :text
#  category   :string
#  published  :boolean          default, false
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :bigint(8)
#

class Info < ApplicationRecord
  extend Enumerize

  belongs_to :author, class_name: "Member" # , foreign_key: "author_id"

  enumerize :category, in: %i[news event management], default: :news
  validates :title, presence: true
end

app/controllers/infos_controller.rb
# frozen_string_literal: true

# Newsfeeds.
class InfosController < ApplicationController
  def index
    @infos = if member_signed_in?
               Info.all.order(updated_at: :desc)
             else
               Info.where(published: true).order(updated_at: :desc)
             end
  end

  def show
    @info = Info.find(params[:id])
  end
end

app/helpers/infos_helper.rb
# frozen_string_literal: true

module InfosHelper # rubocop:disable Style/Documentation
  def infos_of_this_category(infos, category)
    infos.select { |info| info.category == category }
  end
end

app/views/infos/_annonces.html.erb
<div class="card no-border">
  <table class="table table-sm table-hover">
    <tbody>
      <% infos.each do |info| %>
        <tr>
          <td scope="row">
            <%= info.title %>
          </td>
          <td class="d-none d-md-block" scope="row">
            <%= sanitize info.content.truncate(80) %>
          </td>
          <td scope="row">
            <%= link_to "Voir", info_path(info.id), class: "btn btn-base-1 btn-shadow btn-circle px-4" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/infos/index.html.erb
<div class="container mb-4">
  <div class="main-content">

    <div class="page-title">
      <h2 class="heading-infos heading heading-2 text-uppercase border-bottom border-dark strong-800 mt-5 mb-5">
        Infos
      </h2>
    </div>

    <ul class="nav nav-tabs justify-content-center mb-5">
      <li class="nav-item">
        <a class="nav-link active" href="#all-infos" data-toggle="tab" role="tab">
          <%= t(".all_infos") %>
        </a>
      </li>

      <% Info.category.values.each do |category| %>
        <li class="nav-item">
          <a class="nav-link" href="#<%= category %>-info" data-toggle="tab" role="tab">
            <%= category.text %>
          </a>
        </li> 
      <% end %>
    </ul>

    <main class="tab-content" id="myTabContent">
      <section class="tab-pane fade show active" id="all-infos" role="tabpanel" aria-labelledby="all-infos-tab">
        <%= render partial: "annonces", locals: {infos: @infos} %>
      </section>

      <% Info.category.values.each do |category| %>
        <section class="tab-pane fade" id="<%= category %>-info" role="tabpanel" aria-labelledby="<%= category %>-info-tab">
          <div class="tab-content" id="myTabContent">
            <%= render partial: "annonces", locals: {infos: infos_of_this_category(@infos, category)} %>
          </div>
        </section> 
      <% end %>
    </main>
  </div>
</div>

app/views/infos/show.html.erb
<section class="slice sct-color-1">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-8">
				<h3 class="heading heading-1 strong-800 mb-3">
					<%= @info.title %>
				</h3>
				<hr class="mt-0 mb-4">
				<p class="text-md">
    			<%= sanitize @info.content %>
    		</p>
			</div>
		</div>
	</div>
</section>

<div class="mb-4">
	<%= link_to " Retour", infos_path, class: "fas fa-arrow-left link-retour" %>
</div>